<?php

namespace Manuia\Bundle\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LabelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelsRepository extends EntityRepository
{
}
